services:
  - type: web
    name: django-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 825c224c2f59a4d44721f7f88a0f0a3c
      - key: DJANGO_ALLOWED_HOSTS
        value: your-app.onrender.com
