services:
  - type: web
    name: django-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn appTelega.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-q^yw$#&yxmty2d^i@&^2hon=8u$nzgqq-g695a4xj4j9)64rw6
      - key: DJANGO_ALLOWED_HOSTS
        value: your-app.onrender.com
